<?php
$this->headScript()->appendScript(file_get_contents(__DIR__ . '/index.js'));
?>
<h1>Employees and Roles</h1>
<a href="<?=$this->url('inventory', ['controller' => 'employeerole','action' => 'edit'])?>">Add a role to an user</a>
<table>
	<thead>
		<tr>
			<th>code</th>
			<th>employee</th>
			<th>role</th>
		</tr>
	</thead>
	<tbody>
<?php
foreach ($this->employeeRoles as $employeeRole) :
?>
		<tr>
			<td><button id="<?=$employeeRole->code?>" class="edit"><?=$employeeRole->code?></button></td>
			<td><?=$employeeRole->employee->name?></td>
			<td><?=$employeeRole->role->name?></td>
			<td><button id="<?=$employeeRole->code?>" class="delete">delete</button></td>
		</tr>
<?php
endforeach;
?>
	</tbody>
</table>
<span id="api" url="<?=$this->url('inventoryapi',['controller' => 'employeeroleapi'])?>"></span>
<span id="target" url="<?=$this->url('inventory',['controller' => 'employeerole'])?>"></span>
<a href="<?=$this->url('inventory',['controller' => 'menu'])?>">Go back</a>
