<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->headScript()->appendScript(file_get_contents(__DIR__ . '/index.js'));
?>
<p><a href="<?=$this->url('store',['controller' => 'order'])?>">Close order</a></p>
<h1>Product Basket</h1>
<table class="table">
<thead>
<tr>
<th>code</th>
<th>name</th>
<th>price</th>
<th>amount</th>
<th colspan="3">operations</th>
</tr>
</thead>
<tbody>
<?php
$total = 0;
foreach ($this->products as $product):
?>
<tr>
<td><?=$product['code']?></td>
<td><?=$product['name']?></td>
<td><?=$product['price']?></td>
<td><?=$product['amount']?></td>
<td><button class="add" id="<?=$product['code']?>">+</button></td>
<td><button class="sub" id="<?=$product['code']?>">-</button></td>
<td><button class="delete" id="<?=$product['code']?>">remove</button></td>
</tr>
<?php
$total += ($product['price'] * $product['amount']);
endforeach;
?>
</tbody>
<tfoot>
<tr>
<td colspan="3">Total</td>
<td><?=$total?></td>
</tr>
</tfoot>
</table>
<a href="<?=$this->url('store')?>">Keep buying</a>
<span id="api" url="<?=$this->url('storeapi',['controller' => 'productbasketapi'])?>"></span>
<span id="target" url="<?=$this->url('store',['controller' => 'productbasket'])?>"></span>