<?php
$this->headScript()->appendScript(file_get_contents(__DIR__ . '/edit.js'));
?>
<h1>Discount <?=(empty($this->discount->code) ? 'insert' : 'update')?></h1>
<?php
$form = $this->form;
echo $this->form()->openTag($form);
echo $this->formLabel($form->get('name'));
echo $this->formText($form->get('name')) . '<br/>';
echo $this->formLabel($form->get('operator'));
echo $this->formSelect($form->get('operator')) . '<br/>';
echo $this->formLabel($form->get('factor'));
echo $this->formNumber($form->get('factor')) . '<br/>';
echo $this->formHidden($form->get('code'));
echo $this->form()->closeTag();
?>
<button id="save">save</button>
<p>
	<span id="api" url="<?=$this->url('inventoryapi',['controller' => 'discountapi'])?>"></span>
	<span id="target" url="<?=$this->url('inventory',['controller' => 'discount'])?>"></span>
	<a href="<?=$this->url('inventory',['controller' => 'discount'])?>">Go back</a>
</p>
