<?php
$this->headScript()->appendScript(file_get_contents(__DIR__ . '/index.js'));
?>
<h1>Resource Registration</h1>
<a href="<?=$this->url('inventory', ['controller' => 'resource','action' => 'edit'])?>">Add resource</a>
<table>
	<thead>
		<tr>
			<th>code</th>
			<th>name</th>
		</tr>
	</thead>
	<tbody>
<?php
foreach ($this->resources as $resource) :
?>
		<tr>
			<td><button id="<?=$resource->code?>" class="edit"><?=$resource->code?></button></td>
			<td><?=$resource->name?></td>
			<td><?=$resource->nickname?></td>
			<td><button id="<?=$resource->code?>" class="delete">delete</button></td>
		</tr>
<?php
endforeach;
?>
	</tbody>
</table>
<span id="api" url="<?=$this->url('inventoryapi',['controller' => 'resourceapi'])?>"></span>
<span id="target" url="<?=$this->url('inventory',['controller' => 'resource'])?>"></span>
<a href="<?=$this->url('inventory',['controller' => 'menu'])?>">Go back</a>
