<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="card-deck">
    <div class="card">
        <div class="card-body">
            <a class="btn btn-primary" href="<?=$this->url('schoolclass')?>">School classes</a>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <p>
            <a class="btn btn-primary" href="<?=$this->url('student')?>">Students</a>
        </div>
    </div>
</div>
