<?php
$this->headScript()->appendScript(file_get_contents(__DIR__ . '/edit.js'));
?>
<h1>Product <?=(empty($this->product->code) ? 'insert' : 'update')?></h1>
<?php
$form = $this->form;
echo $this->form()->openTag($form);
echo $this->formLabel($form->get('name'));
echo $this->formText($form->get('name')) . '<br/>';
echo $this->formLabel($form->get('price'));
echo $this->formText($form->get('price')) . '<br/>';
echo $this->formLabel($form->get('code_discount'));
echo $this->formSelect($form->get('code_discount')) . '<br/>';
echo $this->formHidden($form->get('code'));
echo $this->form()->closeTag();
?>
<button id="save">save</button>
<p>
	<span id="api" url="<?=$this->url('inventoryapi',['controller' => 'productapi'])?>"></span>
	<span id="target" url="<?=$this->url('inventory',['controller' => 'product'])?>"></span>
	<a href="<?=$this->url('inventory',['controller' => 'product'])?>">Go back</a>
</p>
